name: Build

on:
  workflow_dispatch: {}

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger proxmox-truenas-packer
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.RELEASE_TOKEN }}" \
            https://api.github.com/repos/boomshankerx/proxmox-truenas-packer/dispatches \
            -d '{"event_type": "main-push", "client_payload": {"source": "proxmox-truenas"}}'
